import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import * as S from "./reportSheet.style";
export default function ReportSheet({ isOpen, onClose, risk, onMouseDown, DownloadIcon, }) {
    const Icon = DownloadIcon;
    // 오버레이 클릭으로 닫기
    const handleOverlay = () => onClose();
    return (_jsxs(_Fragment, { children: [_jsx(S.Overlay, { "$isOpen": isOpen, onClick: handleOverlay, onMouseDown: onMouseDown }), _jsxs(S.Sheet, { "$isOpen": isOpen, role: "dialog", "aria-modal": "true", onClick: (e) => e.stopPropagation(), children: [_jsx(S.Title, { children: "\uAC80\uC0AC \uACB0\uACFC \uB9AC\uD3EC\uD2B8" }), _jsxs("div", { style: {
                            display: "flex",
                            justifyContent: "space-between",
                            alignItems: "center",
                        }, children: [_jsx(S.ReasonTitle, { children: "BRIDGE_TO_MIXER" }), _jsx(S.RiskPill, { risk: risk, children: risk === "danger" ? "위험" : risk === "warning" ? "주의" : "정상" })] }), _jsxs(S.Table, { children: [_jsxs(S.ItemWrapper, { children: [_jsx(S.Key, { children: "bridge_out" }), _jsxs(S.ValueContainer, { children: [_jsx(S.Val, { children: "0x....a1" }), _jsx(S.Val, { children: "USDT" }), _jsx(S.Val, { children: "9,980" }), _jsx(S.Val, { children: "23:10" })] })] }), _jsxs(S.ItemWrapper, { children: [_jsx(S.Key, { children: "mixer_deposit" }), _jsxs(S.ValueContainer, { children: [_jsx(S.Val, { children: "0x....b2" }), _jsx(S.Val, { children: "USDT" }), _jsx(S.Val, { children: "9,962" }), _jsx(S.Val, { children: "23:45" })] })] }), _jsx("div", { style: { paddingTop: "40px" } }), _jsxs(S.ItemWrapper, { children: [_jsx(S.Key, { children: "\uD649 \uC218" }), _jsx(S.Val, { children: _jsx("span", { style: { color: "#ffb535" }, children: "2 \u2264 2" }) })] }), _jsxs(S.ItemWrapper, { children: [_jsx(S.Key, { children: "\uC2DC\uAC04 \uAC04\uACA9" }), _jsx(S.Val, { children: _jsx("span", { style: { color: "#21B400" }, children: "35m \u2264 45m" }) })] }), _jsxs(S.ItemWrapper, { children: [_jsx(S.Key, { children: "\uAE08\uC561 \uCC28\uC774\uC728" }), _jsx(S.Val, { children: _jsx("span", { style: { color: "#21B400" }, children: "0.18 \u2264 1.00" }) })] }), _jsx("div", { style: { paddingTop: "40px" } }), _jsxs(S.ItemWrapper, { children: [_jsx(S.Key, { children: "\uC2DC\uAC04" }), _jsx(S.Val, { children: "2025-09-08 14:30" })] }), _jsxs(S.ItemWrapper, { children: [_jsx(S.Key, { children: "\uC815\uCC45" }), _jsx(S.Val, { children: "v1.0.0" })] })] }), _jsx(S.Footer, { children: _jsxs(S.DownloadBtn, { children: [DownloadIcon &&
                                    (typeof DownloadIcon === "string" ? (_jsx("img", { src: DownloadIcon, alt: "\uB2E4\uC6B4\uB85C\uB4DC" })) : (_jsx(Icon, {}))), "\uB2E4\uC6B4\uB85C\uB4DC"] }) })] })] }));
}
